/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.CrewBUS;
import DTO.Crew;
import com.mysql.jdbc.PreparedStatement;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class CrewRefeshGUI extends javax.swing.JFrame {
   
    /**
     * Creates new form CrewRefeshGUI
     */
    AdminView ad = new AdminView();
    public DefaultTableModel model;
    public CrewRefeshGUI() {
        initComponents();
        listCrewdelete();
    }
    public void listCrewdelete() // Chép ArrayList lên table
    {
       
        if(ad.crBUS.getList()== null)ad.crBUS.listCrew();
        ArrayList<Crew> nv = ad.crBUS.getList();
//        model.setRowCount(0);
        outModel(model,nv);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCrewRefesh = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCrewRefesh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới tính", "Loại Nhân Viên", "Số Điện Thoại", "Ca Làm", "Lương", "img"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCrewRefesh.setRowHeight(30);
        tblCrewRefesh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCrewRefeshMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCrewRefesh);

        jButton1.setText("Khôi phục");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCrewRefeshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCrewRefeshMouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel) tblCrewRefesh.getModel();
        int Row = tblCrewRefesh.getSelectedRow();
        if(Row == -1)
        {

        }
        else
        {
            
        }
    }//GEN-LAST:event_tblCrewRefeshMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblCrewRefesh.getModel();
        int Row = tblCrewRefesh.getSelectedRow();
        if(Row == -1)
        {
           JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng để khôi phục");
           return;
        }
        else
        {
            int reply = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn khôi phục không");
            if (reply == JOptionPane.YES_OPTION)
            {
           String id = tblCrewRefesh.getModel().getValueAt(Row, 0).toString();
           ad.crBUS.refeshCREW(id);   
           outModel(model, ad.crBUS.getList());
          
           
        }    
        }        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void outModel(DefaultTableModel model , ArrayList<Crew> cr) // Xuất ra Table từ ArrayList
    {
        model = (DefaultTableModel) tblCrewRefesh.getModel();
        Vector data;
        model.setRowCount(0);
        for(Crew c: cr)
        {
            if(c.getStatus_crew() == 0)
            {
            data = new Vector();
            data.add(c.getId_crew());
            data.add(c.getName_crew());
            data.add(c.getSex());
            data.add(c.getPosition());
            data.add(c.getPhone());
            data.add(c.getSalary());
            data.add(c.getImg());
            model.addRow(data);
            }
        }
        tblCrewRefesh.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCrewRefesh;
    // End of variables declaration//GEN-END:variables
}
